/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Payload__1 = IDL.Record({
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const Id = IDL.Nat;
export const Entry__2 = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const Payload = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'overlayImageUrl' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Entry__1 = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'overlayImageUrl' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Id__1 = IDL.Text;
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
});
export const Entry = IDL.Record({
  'id' : Id__1,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'upiRef' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const Payload__2 = IDL.Record({
  'name' : IDL.Text,
  'blobId' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const Update = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Opt(IDL.Int),
  'blobId' : IDL.Opt(IDL.Text),
  'sizeBytes' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAd' : IDL.Func([Payload__1], [Entry__2], []),
  'createTemplate' : IDL.Func([Payload], [Entry__1], []),
  'deleteAd' : IDL.Func([Id], [], []),
  'deleteScan' : IDL.Func([Id__1], [], []),
  'deleteTemplate' : IDL.Func([Id], [], []),
  'getCallerPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScan' : IDL.Func([Id__1], [Entry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveAds' : IDL.Func([], [IDL.Vec(Entry__2)], ['query']),
  'listActiveTemplates' : IDL.Func([], [IDL.Vec(Entry__1)], ['query']),
  'listAds' : IDL.Func([], [IDL.Vec(Entry__2)], ['query']),
  'listCallerPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'listScans' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'listTemplates' : IDL.Func([], [IDL.Vec(Entry__1)], ['query']),
  'markCallerPremium' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScan' : IDL.Func([Payload__2], [Entry], []),
  'updateAd' : IDL.Func([Id, Payload__1], [], []),
  'updateScan' : IDL.Func([Id__1, Update], [Entry], []),
  'updateTemplate' : IDL.Func([Id, Payload], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Payload__1 = IDL.Record({
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const Id = IDL.Nat;
  const Entry__2 = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const Payload = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'overlayImageUrl' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Entry__1 = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'overlayImageUrl' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Id__1 = IDL.Text;
  const UserProfile = IDL.Record({ 'isPremium' : IDL.Bool, 'name' : IDL.Text });
  const Entry = IDL.Record({
    'id' : Id__1,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'upiRef' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const Payload__2 = IDL.Record({
    'name' : IDL.Text,
    'blobId' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const Update = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Opt(IDL.Int),
    'blobId' : IDL.Opt(IDL.Text),
    'sizeBytes' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAd' : IDL.Func([Payload__1], [Entry__2], []),
    'createTemplate' : IDL.Func([Payload], [Entry__1], []),
    'deleteAd' : IDL.Func([Id], [], []),
    'deleteScan' : IDL.Func([Id__1], [], []),
    'deleteTemplate' : IDL.Func([Id], [], []),
    'getCallerPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScan' : IDL.Func([Id__1], [Entry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveAds' : IDL.Func([], [IDL.Vec(Entry__2)], ['query']),
    'listActiveTemplates' : IDL.Func([], [IDL.Vec(Entry__1)], ['query']),
    'listAds' : IDL.Func([], [IDL.Vec(Entry__2)], ['query']),
    'listCallerPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'listScans' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'listTemplates' : IDL.Func([], [IDL.Vec(Entry__1)], ['query']),
    'markCallerPremium' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScan' : IDL.Func([Payload__2], [Entry], []),
    'updateAd' : IDL.Func([Id, Payload__1], [], []),
    'updateScan' : IDL.Func([Id__1, Update], [Entry], []),
    'updateTemplate' : IDL.Func([Id, Payload], [], []),
  });
};

export const init = ({ IDL }) => { return []; };