/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : Id__1,
  'name' : string,
  'timestamp' : bigint,
  'blobId' : string,
  'sizeBytes' : bigint,
}
export interface Entry__1 {
  'id' : Id,
  'name' : string,
  'description' : string,
  'overlayImageUrl' : string,
  'isActive' : boolean,
}
export interface Entry__2 {
  'id' : Id,
  'title' : string,
  'linkUrl' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export type Id = bigint;
export type Id__1 = string;
export interface Payload {
  'name' : string,
  'description' : string,
  'overlayImageUrl' : string,
  'isActive' : boolean,
}
export interface Payload__1 {
  'title' : string,
  'linkUrl' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface Payload__2 {
  'name' : string,
  'blobId' : string,
  'sizeBytes' : bigint,
}
export interface PaymentRecord {
  'id' : string,
  'userId' : Principal,
  'upiRef' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface Update {
  'name' : [] | [string],
  'timestamp' : [] | [bigint],
  'blobId' : [] | [string],
  'sizeBytes' : [] | [bigint],
}
export interface UserProfile { 'isPremium' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAd' : ActorMethod<[Payload__1], Entry__2>,
  'createTemplate' : ActorMethod<[Payload], Entry__1>,
  'deleteAd' : ActorMethod<[Id], undefined>,
  'deleteScan' : ActorMethod<[Id__1], undefined>,
  'deleteTemplate' : ActorMethod<[Id], undefined>,
  'getCallerPremiumStatus' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScan' : ActorMethod<[Id__1], Entry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveAds' : ActorMethod<[], Array<Entry__2>>,
  'listActiveTemplates' : ActorMethod<[], Array<Entry__1>>,
  'listAds' : ActorMethod<[], Array<Entry__2>>,
  'listCallerPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'listScans' : ActorMethod<[], Array<Entry>>,
  'listTemplates' : ActorMethod<[], Array<Entry__1>>,
  'markCallerPremium' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveScan' : ActorMethod<[Payload__2], Entry>,
  'updateAd' : ActorMethod<[Id, Payload__1], undefined>,
  'updateScan' : ActorMethod<[Id__1, Update], Entry>,
  'updateTemplate' : ActorMethod<[Id, Payload], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];